---
kind: pipeline
name: default

steps:
- name: build
  image: docker:20.10.17-dind
  environment:
    GOPATH: /go
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/go/bin
  commands:
  - /usr/local/bin/dockerd-entrypoint.sh &
  - apk add -U bash make gcc musl-dev git wget go curl 
  - mkdir -p /go/src/github.com/rancher
  - ln -s /drone/src /go/src/github.com/rancher/terraform-provider-rancher2
  - cd /go/src/github.com/rancher/terraform-provider-rancher2
  - make docker-build
  - make docker-testacc
  - kill %1
  privileged: true

- name: build-all-binaries
  image: golang:1.19.4
  environment:
    CROSS: 1
    VERSION: ${DRONE_TAG}
  commands:
  - apt-get update
  - apt-get install -y xz-utils zip rsync jq curl ca-certificates
  - mkdir -p /go/src/github.com/rancher
  - ln -s /drone/src /go/src/github.com/rancher/terraform-provider-rancher2
  - cd /go/src/github.com/rancher/terraform-provider-rancher2
  - make build-rancher
  - make package-rancher
  when:
    event: tag

- name: gpg_sign_release  
  image: plugins/gpgsign
  settings:
    key:
      from_secret: gpg_key
    passphrase:
      from_secret: gpg_passphrase
    files:
      - dist/artifacts/${DRONE_TAG}/terraform-provider-rancher2_*_SHA256SUMS
    detach_sign: true
    armor: false
  when:
    event: tag

- name: github_binary_prerelease
  image: plugins/github-release
  settings:
    prerelease: true
    files:
    - dist/artifacts/${DRONE_TAG}/terraform-provider-rancher2_*
    api_key: 
      from_secret: github_token
  when:
    event: tag
    ref:
      include: [ refs/tags/*rc* ]

- name: github_binary_release
  image: plugins/github-release
  settings:
    files:
    - dist/artifacts/${DRONE_TAG}/terraform-provider-rancher2_*
    api_key: 
      from_secret: github_token
  when:
    event: tag
    ref:
      exclude: [ refs/tags/*rc* ]