package rancher2_dev

import (
	"bytes"
	"math/big"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	h "github.com/rancher/terraform-provider-rancher2/internal/provider/test_helpers"
)

func TestRancherDevModel(t *testing.T) {
	t.Run("ToResource", func(t *testing.T) {

		nestedNestedObjectValue := types.ObjectValueMust(
			nestedNestedObjectAttrTypes,
			map[string]attr.Value{
				"string_attribute": types.StringValue("test"),
				"bool_attribute":   types.BoolValue(true),
			},
		)

		nestedObjectValue := types.ObjectValueMust(
			nestedObjectAttrTypes,
			map[string]attr.Value{
				"string_attribute":     types.StringValue("test"),
				"nested_nested_object": nestedNestedObjectValue,
			},
		)

		testCases := []struct {
			name string
			fit  RancherDevModel
			want RancherDevResourceModel
		}{
			{
				"Basic",
				RancherDevModel{
					ID:               "test",             // usually generated by the provider, but not here
					StringAttribute:  "test",             // required
					NumberAttribute:  big.NewFloat(1.23), // required
					Identifier:       "test",             // read only
					Int32Attribute:   int32(123),         // read only
					BoolAttribute:    true,
					Int64Attribute:   int64(123),
					Float64Attribute: 1.23,
					Float32Attribute: float32(1.23),
					ListAttribute:    []string{"test"},
					SetAttribute:     map[string]bool{"test": true},
					MapAttribute:     map[string]string{"test": "test"},
					NestedObject: NestedObject{
						StringAttribute: "test",
						NestedNestedObject: NestedNestedObject{
							StringAttribute: "test",
							BoolAttribute:   true,
						},
					},
					NestedObjectList: []NestedObject{
						{
							StringAttribute: "test",
							NestedNestedObject: NestedNestedObject{
								StringAttribute: "test",
								BoolAttribute:   true,
							},
						},
					},
					NestedObjectMap: map[string]NestedObject{
						"test": {
							StringAttribute: "test",
							NestedNestedObject: NestedNestedObject{
								StringAttribute: "test",
								BoolAttribute:   true,
							},
						},
					},
				},
				RancherDevResourceModel{
					ID:               types.StringValue("test"), // usually generated by the provider
					Identifier:       types.StringValue("test"),
					NumberAttribute:  types.NumberValue(big.NewFloat(1.23)),
					StringAttribute:  types.StringValue("test"),
					Int32Attribute:   types.Int32Value(123),
					BoolAttribute:    types.BoolValue(true),
					Int64Attribute:   types.Int64Value(123),
					Float64Attribute: types.Float64Value(1.23),
					Float32Attribute: types.Float32Value(1.23),
					ListAttribute:    types.ListValueMust(types.StringType, []attr.Value{types.StringValue("test")}),
					SetAttribute:     types.SetValueMust(types.StringType, []attr.Value{types.StringValue("test")}),
					MapAttribute:     types.MapValueMust(types.StringType, map[string]attr.Value{"test": types.StringValue("test")}),
					NestedObject:     nestedObjectValue,
					NestedObjectList: types.ListValueMust(
						types.ObjectType{AttrTypes: nestedObjectAttrTypes},
						[]attr.Value{nestedObjectValue},
					),
					NestedObjectMap: types.MapValueMust(
						types.ObjectType{AttrTypes: nestedObjectAttrTypes},
						map[string]attr.Value{"test": nestedObjectValue},
					),
				},
			},
		}
		for _, tc := range testCases {
			t.Run(tc.name, func(t *testing.T) {
				var buf bytes.Buffer
				defer h.PrintLog(t, &buf, "ERROR") // this enables tflog.Debug, change to DEBUG when troubleshooting
				ctx := h.GenerateTestContext(t, &buf, nil)

				got := tc.fit.ToResourceModel(ctx, &diag.Diagnostics{})
				if diff := cmp.Diff(tc.want, *got, cmp.AllowUnexported(tftypes.Value{}, big.Float{})); diff != "" {
					t.Errorf("unexpected diff (-want, +got) = %s", diff)
				}
			})
		}
	})
}

func TestNestedObject(t *testing.T) {
	t.Run("ToResource", func(t *testing.T) {
		nestedNestedObjectValue := types.ObjectValueMust(
			nestedNestedObjectAttrTypes,
			map[string]attr.Value{
				"string_attribute": types.StringValue("test"),
				"bool_attribute":   types.BoolValue(true),
			},
		)

		testCases := []struct {
			name string
			fit  NestedObject
			want NestedResourceModel
		}{
			{
				"Basic",
				NestedObject{
					StringAttribute: "test",
					NestedNestedObject: NestedNestedObject{
						StringAttribute: "test",
						BoolAttribute:   true,
					},
				},
				NestedResourceModel{
					StringAttribute:    types.StringValue("test"),
					NestedNestedObject: nestedNestedObjectValue,
				},
			},
		}
		for _, tc := range testCases {
			t.Run(tc.name, func(t *testing.T) {
				var buf bytes.Buffer
				defer h.PrintLog(t, &buf, "ERROR") // this enables tflog.Debug, change to DEBUG when troubleshooting
				ctx := h.GenerateTestContext(t, &buf, nil)

				got := NestedResourceModel{}
				tc.fit.ToResourceModel(ctx, &got)
				if diff := cmp.Diff(tc.want, got, cmp.AllowUnexported(tftypes.Value{})); diff != "" {
					t.Errorf("unexpected diff (-want, +got) = %s", diff)
				}
			})
		}
	})
}

func TestNestedNestedObject(t *testing.T) {
	t.Run("ToResource", func(t *testing.T) {
		testCases := []struct {
			name string
			fit  NestedNestedObject
			want NestedNestedResourceModel
		}{
			{
				"Basic",
				NestedNestedObject{
					StringAttribute: "test",
					BoolAttribute:   true,
				},
				NestedNestedResourceModel{
					StringAttribute: types.StringValue("test"),
					BoolAttribute:   types.BoolValue(true),
				},
			},
		}
		for _, tc := range testCases {
			t.Run(tc.name, func(t *testing.T) {
				var buf bytes.Buffer
				defer h.PrintLog(t, &buf, "ERROR") // this enables tflog.Debug, change to DEBUG when troubleshooting
				ctx := h.GenerateTestContext(t, &buf, nil)

				got := NestedNestedResourceModel{}
				tc.fit.ToResourceModel(ctx, &got)
				if got != tc.want {
					t.Errorf("got %v, want %v", got, tc.want)
				}
			})
		}
	})
}
