package rancher2

import (
	"github.com/hashicorp/terraform-plugin-sdk/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/helper/validation"
	"github.com/rancher/rancher/pkg/capr"
)

func clusterV2RKEConfigMachinePoolDefaultFields() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"hostname_length_limit": {
			Type:         schema.TypeInt,
			Optional:     true,
			Description:  "maximum length for autogenerated hostname",
			ValidateFunc: validation.IntBetween(capr.MinimumHostnameLengthLimit, capr.MaximumHostnameLengthLimit),
		},
	}
}
