#!/usr/bin/env bash
#
# Skill: create-pr.sh
# Description: Safely creates a pull request from your local fork branch to the upstream main branch,
#              bypassing ambient GITHUB_TOKEN environment overrides to use the gh CLI's authenticated credential.
#              This acts as a lightweight controller, importing and coordinating modular operations under agent-scripts/.
# Usage: .gemini/skills/create-pr.sh --title "<Title>" --body "<Body>" [--base "<Base>"] [--draft]

set -euo pipefail

# Locate absolute directory path of the workspace root dynamically
WORKSPACE_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || pwd)

# Source modular utilities from agent-scripts/
# shellcheck source=agent-scripts/pr-helper.sh
source "${WORKSPACE_ROOT}/agent-scripts/pr-helper.sh"

show_help() {
  cat <<EOF
Usage: create-pr.sh [options]

Safely creates or graduates a pull request from your local fork branch to the upstream repository.

Options:
  --title TITLE        The title of the pull request (Required for creation).
  --body BODY          The markdown description body of the pull request (Required for creation).
  --base BASE          The target upstream branch (default: main).
  --draft              Create the pull request as a draft.
  --ready [TARGET]     Graduate a draft pull request to ready-for-review (accepts PR number, branch, or URL; defaults to current branch).
  -h, --help           Show this help message and exit.
EOF
}

verify_git_env() {
  if ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    echo "Error: This command must be run inside a Git repository." >&2
    exit 1
  fi
}

main() {
  local title=""
  local body=""
  local base="main"
  local draft_flag=""
  local action="create"
  local ready_target=""

  while [[ $# -gt 0 ]]; do
    case "$1" in
      -h|--help)
        show_help
        exit 0
        ;;
      --title)
        if [[ -z "${2:-}" ]]; then
          echo "Error: --title requires an argument." >&2
          exit 1
        fi
        title="$2"
        shift 2
        ;;
      --body)
        if [[ -z "${2:-}" ]]; then
          echo "Error: --body requires an argument." >&2
          exit 1
        fi
        body="$2"
        shift 2
        ;;
      --base)
        if [[ -z "${2:-}" ]]; then
          echo "Error: --base requires an argument." >&2
          exit 1
        fi
        base="$2"
        shift 2
        ;;
      --draft)
        draft_flag="--draft"
        shift
        ;;
      --ready)
        action="ready"
        if [[ $# -gt 1 && ! "$2" =~ ^- ]]; then
          ready_target="$2"
          shift 2
        else
          ready_target=""
          shift
        fi
        ;;
      *)
        echo "Unknown parameter: $1" >&2
        show_help
        exit 1
        ;;
    esac
  done

  if [[ "$action" == "ready" ]]; then
    verify_git_env
    graduate_pull_request "$ready_target"
    exit 0
  fi

  if [[ -z "$title" ]]; then
    title=$(git log -1 --pretty=%s 2>/dev/null || true)
    if [[ -z "$title" ]]; then
      title="chore: automated development pull request"
    fi
  fi

  if [[ -z "$body" ]]; then
    body=$(git log -1 --pretty=%b 2>/dev/null || true)
    if [[ -z "$body" ]]; then
      body="Automated Draft Pull Request generated by the Agentic Framework."
    fi
  fi

  verify_git_env
  create_pull_request "$title" "$body" "$base" "$draft_flag"
}

main "$@"
