#!/bin/bash

set -x

if [ -f /tmp/testacc_docker_id ]; then
	echo Cleaning up rancher server docker
	docker rm -fv $(cat /tmp/testacc_docker_id)
	rm /tmp/testacc_docker_id
fi

if [ -f /tmp/rke_cluster.yml ]; then
	echo Cleaning up rke dind cluster
	rke remove --dind --force --config /tmp/rke_cluster.yml
	rm /tmp/rke_cluster.yml
fi
