#!/bin/bash

set -x
server=$(docker run -d -p 8443:443 rancher/rancher:latest)
#server=elated_benz
server_ip=$(docker inspect ${server} -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}')
#server_ip=10.20.0.4
export RANCHER_URL=https://${server_ip}:8443

cat<<EOF>>/tmp/rke_cluster.yml
ingress:
  node_selector:
    app: ingress
network:
  plugin: calico
nodes:
  - address: node-0
    role: [etcd,controlplane,worker]
    user: ubuntu
EOF

rke up --config /tmp/rke_cluster.yml --dind
export KUBE_CONFIG="$(dirname $0)/kube_config_rke_cluster.yml"

password=$(docker exec -it ${server} reset-password | grep -v '^New'|tr -d '\r')

USERTOKEN=$(curl -X POST -k "${RANCHER_URL}/v3-public/localProviders/local?action=login" \
    -H 'Accept: application/json' \
    -H 'Content-Type: application/json' \
    --data-binary "{\"password\":\"${password}\",\"username\":\"admin\"}"|jq -r .token)

curl -X PUT -k "${RANCHER_URL}/v3/settings/server-url" \
    -H 'Accept: application/json' \
    -H "Authorization: Bearer ${USERTOKEN}" \
    -H 'Content-Type: application/json' \
    --data-binary "{\"name\": \"server-url\", \"value\":\"${RANCHER_URL}\"}"

read -r -d '' cluster_json << EOM
{
  "type": "cluster",
  "dockerRootDir": "/var/lib/docker",
  "enableNetworkPolicy": "false",
  "name": "bootstrap-imported-rke-cluster"
}
EOM

cluster_obj=$(curl -k -X POST -H "Authorization: Bearer ${USERTOKEN}" \
    -H 'Accept: application/json' \
    -H 'Content-Type: application/json' \
    ${RANCHER_URL}/v3/clusters \
    -d "${cluster_json}")

cluster_id=$(echo $cluster_obj|jq -r '.id')
registration_link=$(echo $cluster_obj|jq -r '.links.clusterRegistrationTokens')

curl -k -X POST -H "Authorization: Bearer ${USERTOKEN}" \
    -H 'Accept: application/json' \
    -H 'Content-Type: application/json' \
    ${RANCHER_URL}/v3/clusterregistrationtoken \
    -d "{\"clusterId\": \"${cluster_id}\", \"type\":\"clusterRegistrationToken\"}"
sleep 1

reg_command=$(curl -k -X GET -H "Authorization: Bearer ${USERTOKEN}" \
    -H 'Accept: application/json' \
    -H 'Content-Type: application/json' \
    ${registration_link}| jq -r '.data[0].insecureCommand')

${reg_command}
