#!/bin/bash
set -e

RANCHER_URL=${RANCHER_URL:-""}
RANCHER_TOKEN_KEY=${RANCHER_TOKEN_KEY:-""}
RANCHER_ACCESS_KEY=${RANCHER_ACCESS_KEY:-""}
RANCHER_SECRET_KEY=${RANCHER_SECRET_KEY:-""}

cd $(dirname $0)/..

echo Running acceptance tests

PACKAGES="$(find . -name '*.go' | xargs -I{} dirname {} |  cut -f2 -d/ | sort -u | grep -Ev '(^\.$|.git|.trash-cache|vendor|bin)' | sed -e 's!^!./!' -e 's!$!/...!')"

TF_ACC=1 go test -race -cover -tags=test ${PACKAGES} -v -timeout 120m