#!/bin/bash
set -e

current_dir=$(pwd)

cleanup()
{
    ${current_dir}/cleanup_rancher
}
trap cleanup EXIT TERM ERR

source $(dirname $0)/start_rancher

RANCHER_URL=${RANCHER_URL:-""}
RANCHER_TOKEN_KEY=${RANCHER_TOKEN_KEY:-""}
RANCHER_ACCESS_KEY=${RANCHER_ACCESS_KEY:-""}
RANCHER_SECRET_KEY=${RANCHER_SECRET_KEY:-""}
RANCHER_INSECURE=${RANCHER_INSECURE:-"false"}
RANCHER_ACC_CLUSTER_NAME=${RANCHER_ACC_CLUSTER_NAME:-"local"}

cd $(dirname $0)/..

echo Running acceptance tests

PACKAGES="$(find . -name '*.go' | xargs -I{} dirname {} |  cut -f2 -d/ | sort -u | grep -Ev '(^\.$|.git|.trash-cache|vendor|bin)' | sed -e 's!^!./!' -e 's!$!/...!')"

TF_ACC=1 go test -race -cover -tags=test ${PACKAGES} -v -timeout 120m
