name: Manually Create RC Release
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'The branch where the sha exists.'
        required: true
      sha:
        description: 'The commit SHA to create the tag from, defaults to HEAD of the selected branch.'
        required: false
      tag:
        description: 'The rc tag to create, e.g. v1.2.3-rc.1'
        required: true

permissions: {}

jobs:
  rc-release:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rancher/ci-image/nix:20260603-18
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
      actions: read
    steps:
      - name: Checkout Repository
        id: checkout-repository
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - name: Check Author
        id: check-user-in-maintainers
        # https://github.com/actions/github-script/releases
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MAINTAINERS: ${{ vars.TERRAFORM_MAINTAINERS }}
          SCRIPT_MODE: check-maintainer
        with:
          script: |
            const scriptPath = `${process.env.GITHUB_WORKSPACE}/.github/workflows/scripts/releases.js`;
            const { default: script } = await import(scriptPath);
            const isMaintainer = await script({github, context, core, process});
            if (!isMaintainer) {
              core.setFailed(`User ${context.actor} is not authorized to trigger this workflow.`);
            }
      - name: Verify Tag
        id: verify-tag
        env:
          TAG: ${{ inputs.tag }}
        run: |
          # if the tag doesn't contain "rc" we should not be in this workflow
          if grep -q "rc" <<< "$TAG"; then
            echo "Tag contains 'rc', continuing with RC release"
          else
            echo "Tag doesn't contain 'rc', please use the manual-release workflow"
            exit 1
          fi
      - name: Create and Push RC Tag with Git
        id: create-push-rc-tag
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          TAG: ${{ inputs.tag }}
          SHA: ${{ inputs.sha }}
        run: |
          git config --global --add safe.directory "$PWD"
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          if [ -n "$SHA" ]; then
            git tag "$TAG" -m "Release Candidate $TAG" "$SHA"
          else
            git tag "$TAG" -m "Release Candidate $TAG"
          fi
          git push origin "$TAG"
      - name: Check out new tag into a new directory
        id: checkout-new-tag
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ inputs.tag }}
          path: ${{ github.workspace }}/tags/${{ inputs.tag }}
      - name: Prepare Registry Manifest
        id: prepare-registry-manifest
        env:
          WORKSPACE: ${{ github.workspace }}
          TAG: ${{ inputs.tag }}
        run: |
          # remove any tags that are not the one specified (to avoid goreleaser confusion)
          DIR="$(pwd)"
          cd "$WORKSPACE/tags/$TAG"
          tags_to_delete=$(git tag | grep -v -e "^$TAG$")
          if [ -n "$tags_to_delete" ]; then
            echo "$tags_to_delete" | xargs git tag -d
          fi
          # check for terraform-registry-manifest.json presence and create if missing
          if [ ! -f "terraform-registry-manifest.json" ]; then
            echo "terraform-registry-manifest.json not found, creating a default one."
            cat <<EOF > terraform-registry-manifest.json
          {
              "version": 1,
              "metadata": {
                  "protocol_versions": ["4.0", "5.0", "6.0"]
              }
          }
          EOF
          fi
          cd "$DIR"
      - name: retrieve GPG Credentials
        id: retrieve-gpg-credentials
        # https://github.com/rancher-eio/read-vault-secrets/commits
        uses: rancher-eio/read-vault-secrets@7282bf97898cd1c16c89f837e0bb442e6d384c89 # main
        with:
          secrets: |
            secret/data/github/repo/${{ github.repository }}/signing/gpg passphrase | GPG_PASSPHRASE ;
            secret/data/github/repo/${{ github.repository }}/signing/gpg privateKeyId | GPG_KEY_ID ;
            secret/data/github/repo/${{ github.repository }}/signing/gpg privateKey | GPG_KEY
      - name: import_gpg_key
        id: import-gpg-key
        env:
          GPG_PASSPHRASE: ${{ env.GPG_PASSPHRASE }}
          GPG_KEY_ID: ${{ env.GPG_KEY_ID }}
          GPG_KEY: ${{ env.GPG_KEY }}
        run: |
          cleanup() {
            # clear history just in case
            history -c
          }
          trap cleanup EXIT TERM

          # sanitize variables
          if [ -z "${GPG_PASSPHRASE}" ]; then echo "gpg passphrase empty"; exit 1; fi
          if [ -z "${GPG_KEY_ID}" ]; then echo "key id empty"; exit 1; fi
          if [ -z "${GPG_KEY}" ]; then echo "key contents empty"; exit 1; fi

          echo "Importing gpg key"
          echo "${GPG_KEY}" | gpg --import --batch > /dev/null || { echo "Failed to import GPG key"; exit 1; }
      - name: Run GoReleaser
        id: run-goreleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_KEY_ID: ${{ env.GPG_KEY_ID }}
          GPG_PASSPHRASE: ${{ env.GPG_PASSPHRASE }}
          TAG: ${{ inputs.tag }}
        run: .github/workflows/scripts/nix-run.sh bash -c "cd \"\$GITHUB_WORKSPACE/tags/\$TAG\" && goreleaser release --clean --skip=validate --config ../../.goreleaser_rc.yml"
      - name: 'Find Issues and Create Comments'
        id: find-issues-create-comments
        # https://github.com/actions/github-script/releases
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          TAG: ${{ inputs.tag }}
          BRANCH: ${{ inputs.branch }}
          SCRIPT_MODE: rc-notify
        with:
          script: |
            const scriptPath = `${process.env.GITHUB_WORKSPACE}/.github/workflows/scripts/releases.js`;
            const { default: script } = await import(scriptPath);
            await script({github, context, core, process});
